name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.0
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '12266719'
        packages: 'platforms;android-35 build-tools;35.0.0 platform-tools'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --channel=0 \
          --install "ndk;28.2.13676358"
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> $GITHUB_ENV
        sed -i '10i\
        \
            ndkVersion = "28.2.13676358"' ${{ github.workspace }}/V2rayNG/app/build.gradle.kts

    # مرحله ۱: ساخت اجباری Tun2Socks (بدون کش)
    - name: Build libtun2socks
      run: |
        chmod +x compile-tun2socks.sh
        chmod +x compile-hevtun.sh
        bash compile-tun2socks.sh
        bash compile-hevtun.sh
    
    # مرحله ۲: ساخت پوشه libs در پروژه اندروید
    - name: Prepare Libs Directory
      run: |
        mkdir -p ${{ github.workspace }}/V2rayNG/app/libs

    # مرحله ۳: کپی کردن فایل‌های ساخته شده (tun2socks) به داخل پروژه
    - name: Copy Built Libs
      run: |
        echo "Copying built libraries..."
        # کپی محتویات پوشه libs ریشه به داخل app/libs
        cp -r ${{ github.workspace }}/libs/* ${{ github.workspace }}/V2rayNG/app/libs/
        ls -R ${{ github.workspace }}/V2rayNG/app/libs/

    # مرحله ۴: دانلود libv2ray سالم
    - name: Download libv2ray
      run: |
        echo "Downloading libv2ray.aar..."
        wget -O ${{ github.workspace }}/V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/download/v25.12.8/libv2ray.aar

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        chmod 755 gradlew
        ./gradlew assembleRelease
    
    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: arm64-v8a
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*arm64-v8a*.apk

    - name: Upload armeabi-v7a APK
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: armeabi-v7a
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*armeabi-v7a*.apk

    - name: Upload x86 APK
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: x86-apk
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*x86*.apk